### ISSUE TITLE
请对要导出自己训练的模型，export.py需要做哪些修改呢

### ISSUE THREAD

**Issue by wj1017090777** [hpc203/yolov7-opencv-onnxrun-cpp-py#6]
我将您仓库的yolov7_640x640.onnx与yolov7.onnx对比[转换脚本](https://github.com/WongKinYiu/yolov7/blob/main/models/export.py)，用netron可视化后，发现有很多不同，官方脚本Mul_976会报错，而您的yolov7_640x640.onnx 没有Mul_976节点，请问我该如何修改export.py脚本呢

**Comment by wj1017090777** [comment]
我用最新的pytorch、onnx、onnx-simplifier能导出成功，并能获得推理结果

**Comment by 315386775** [comment]
export.py需要怎么修改吗

**Comment by weiqwert** [comment]
> 我用最新的pytorch、onnx、onnx-simplifier能导出成功，并能获得推理结果

想知道你是怎么解决的，希望能够解答一下。我导出的onnx模型和去网上down下来的不太一样

**Comment by wj1017090777** [comment]
我当时没有修改任何东西，直接在colab git最新的分支，用yolov7提供的脚本就能转换成功，也能用此仓库onnxruntime推理成功。不过现在yolov7又修改了很多，不知道还能否转换成功。建议用colab尝试转换，在自己的环境转换坑太多了。另外，此仓库的模型部分应该来自[](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7)

**Comment by wj1017090777** [comment]
我当时没有修改任何东西，直接在colab git最新的分支，用yolov7提供的脚本就能转换成功，也能用此仓库onnxruntime推理成功。不过现在yolov7又修改了很多，不知道还能否转换成功。建议用colab尝试转换，在自己的环境转换坑太多了。另外，此仓库的模型部分应该来自[https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7](yolov7)

**Comment by wj1017090777** [comment]
我没有修改任何文件。我当时git yolov7最新的分支，在colab上导出成功，netron可视化结构也不一样，但能用该仓库的onnxruntime代码推理成功，并且输出结果一样。目前yolov7修改了很过，不知道能否转换成功。建议在colab上进行转换，本地转换环境坑太多。另外，该仓库部分onnx文件，应该来自[yolov7_onnx](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7)

**Comment by wj1017090777** [comment]
我没有修改任何文件。我当时git yolov7最新的分支，在colab上导出成功，netron可视化结构也不一样，但能用该仓库的onnxruntime代码推理成功，并且输出结果一样。目前yolov7修改了很过，不知道能否转换成功。建议在colab上进行转换，本地转换环境坑太多。另外，[yolov7_onnx](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7)，有onnx文件以及例子，可以参考一下
